version: "3.8"

services:
  database:
    container_name: ecommerce_fiber_db
    image: postgres:15.2
    environment:
      POSTGRES_USER: holyraven
      POSTGRES_PASSWORD: holyraven
      POSTGRES_DB: ecommerce_fiber
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U holyraven -d ecommerce_fiber"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_fiber_api
    depends_on:
      - database
    ports:
      - '8000:8000'
    restart: always
    environment:
      - JWT_SECRET=mamangRust
      - DB_DRIVER=postgres
      - DB_USER=holyraven
      - DB_PASSWORD=holyraven
      - DB_NAME=ecommerce_fiber
      - DB_PORT=5432
      - PORT=5000

volumes:
  db: