// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: rajaongkir.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryProvinsi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QueryProvinsi) Reset() {
	*x = QueryProvinsi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProvinsi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProvinsi) ProtoMessage() {}

func (x *QueryProvinsi) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProvinsi.ProtoReflect.Descriptor instead.
func (*QueryProvinsi) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{0}
}

func (x *QueryProvinsi) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusProvinsi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StatusProvinsi) Reset() {
	*x = StatusProvinsi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusProvinsi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusProvinsi) ProtoMessage() {}

func (x *StatusProvinsi) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusProvinsi.ProtoReflect.Descriptor instead.
func (*StatusProvinsi) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{1}
}

func (x *StatusProvinsi) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusProvinsi) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ResultsProvinsi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvinceId string `protobuf:"bytes,1,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province   string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
}

func (x *ResultsProvinsi) Reset() {
	*x = ResultsProvinsi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultsProvinsi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsProvinsi) ProtoMessage() {}

func (x *ResultsProvinsi) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsProvinsi.ProtoReflect.Descriptor instead.
func (*ResultsProvinsi) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{2}
}

func (x *ResultsProvinsi) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *ResultsProvinsi) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

type RajaOngkirResponseProvinsi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rajaongkir *RajaOngkirResponseProvinsi_Rajaongkir `protobuf:"bytes,1,opt,name=rajaongkir,proto3" json:"rajaongkir,omitempty"`
}

func (x *RajaOngkirResponseProvinsi) Reset() {
	*x = RajaOngkirResponseProvinsi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirResponseProvinsi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirResponseProvinsi) ProtoMessage() {}

func (x *RajaOngkirResponseProvinsi) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirResponseProvinsi.ProtoReflect.Descriptor instead.
func (*RajaOngkirResponseProvinsi) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{3}
}

func (x *RajaOngkirResponseProvinsi) GetRajaongkir() *RajaOngkirResponseProvinsi_Rajaongkir {
	if x != nil {
		return x.Rajaongkir
	}
	return nil
}

type QueryCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Province string `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *QueryCity) Reset() {
	*x = QueryCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCity) ProtoMessage() {}

func (x *QueryCity) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCity.ProtoReflect.Descriptor instead.
func (*QueryCity) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCity) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *QueryCity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *StatusCity) Reset() {
	*x = StatusCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCity) ProtoMessage() {}

func (x *StatusCity) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCity.ProtoReflect.Descriptor instead.
func (*StatusCity) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{5}
}

func (x *StatusCity) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StatusCity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ResultsCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId     string `protobuf:"bytes,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	ProvinceId string `protobuf:"bytes,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province   string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CityName   string `protobuf:"bytes,5,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	PostalCode string `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
}

func (x *ResultsCity) Reset() {
	*x = ResultsCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultsCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsCity) ProtoMessage() {}

func (x *ResultsCity) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsCity.ProtoReflect.Descriptor instead.
func (*ResultsCity) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{6}
}

func (x *ResultsCity) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *ResultsCity) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *ResultsCity) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ResultsCity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResultsCity) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *ResultsCity) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type RajaOngkirCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rajaongkir *RajaOngkirCityResponse_Rajaongkir `protobuf:"bytes,1,opt,name=rajaongkir,proto3" json:"rajaongkir,omitempty"`
}

func (x *RajaOngkirCityResponse) Reset() {
	*x = RajaOngkirCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirCityResponse) ProtoMessage() {}

func (x *RajaOngkirCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirCityResponse.ProtoReflect.Descriptor instead.
func (*RajaOngkirCityResponse) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{7}
}

func (x *RajaOngkirCityResponse) GetRajaongkir() *RajaOngkirCityResponse_Rajaongkir {
	if x != nil {
		return x.Rajaongkir
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Weight      int32  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Courier     string `protobuf:"bytes,4,opt,name=courier,proto3" json:"courier,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{8}
}

func (x *Query) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Query) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Query) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Query) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{9}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CityDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId     string `protobuf:"bytes,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	ProvinceId string `protobuf:"bytes,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province   string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CityName   string `protobuf:"bytes,5,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	PostalCode string `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
}

func (x *CityDetails) Reset() {
	*x = CityDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityDetails) ProtoMessage() {}

func (x *CityDetails) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityDetails.ProtoReflect.Descriptor instead.
func (*CityDetails) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{10}
}

func (x *CityDetails) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CityDetails) GetProvinceId() string {
	if x != nil {
		return x.ProvinceId
	}
	return ""
}

func (x *CityDetails) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CityDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CityDetails) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *CityDetails) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type CostDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Etd   string `protobuf:"bytes,2,opt,name=etd,proto3" json:"etd,omitempty"`
	Note  string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *CostDetail) Reset() {
	*x = CostDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostDetail) ProtoMessage() {}

func (x *CostDetail) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostDetail.ProtoReflect.Descriptor instead.
func (*CostDetail) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{11}
}

func (x *CostDetail) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CostDetail) GetEtd() string {
	if x != nil {
		return x.Etd
	}
	return ""
}

func (x *CostDetail) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Cost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service     string        `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CostDetails []*CostDetail `protobuf:"bytes,3,rep,name=cost_details,json=costDetails,proto3" json:"cost_details,omitempty"`
}

func (x *Cost) Reset() {
	*x = Cost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cost) ProtoMessage() {}

func (x *Cost) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cost.ProtoReflect.Descriptor instead.
func (*Cost) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{12}
}

func (x *Cost) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Cost) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cost) GetCostDetails() []*CostDetail {
	if x != nil {
		return x.CostDetails
	}
	return nil
}

type CourierResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string  `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Costs []*Cost `protobuf:"bytes,3,rep,name=costs,proto3" json:"costs,omitempty"`
}

func (x *CourierResult) Reset() {
	*x = CourierResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierResult) ProtoMessage() {}

func (x *CourierResult) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierResult.ProtoReflect.Descriptor instead.
func (*CourierResult) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{13}
}

func (x *CourierResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CourierResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CourierResult) GetCosts() []*Cost {
	if x != nil {
		return x.Costs
	}
	return nil
}

type RajaOngkirOngkosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rajaongkir *RajaOngkirOngkosResponse_RajaOngkir `protobuf:"bytes,1,opt,name=rajaongkir,proto3" json:"rajaongkir,omitempty"`
}

func (x *RajaOngkirOngkosResponse) Reset() {
	*x = RajaOngkirOngkosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirOngkosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirOngkosResponse) ProtoMessage() {}

func (x *RajaOngkirOngkosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirOngkosResponse.ProtoReflect.Descriptor instead.
func (*RajaOngkirOngkosResponse) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{14}
}

func (x *RajaOngkirOngkosResponse) GetRajaongkir() *RajaOngkirOngkosResponse_RajaOngkir {
	if x != nil {
		return x.Rajaongkir
	}
	return nil
}

type CityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CityRequest) Reset() {
	*x = CityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityRequest) ProtoMessage() {}

func (x *CityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityRequest.ProtoReflect.Descriptor instead.
func (*CityRequest) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{15}
}

func (x *CityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OngkosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asal   string `protobuf:"bytes,1,opt,name=asal,proto3" json:"asal,omitempty"`
	Tujuan string `protobuf:"bytes,2,opt,name=tujuan,proto3" json:"tujuan,omitempty"`
	Berat  int32  `protobuf:"varint,3,opt,name=berat,proto3" json:"berat,omitempty"`
	Kurir  string `protobuf:"bytes,4,opt,name=kurir,proto3" json:"kurir,omitempty"`
}

func (x *OngkosRequest) Reset() {
	*x = OngkosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OngkosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OngkosRequest) ProtoMessage() {}

func (x *OngkosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OngkosRequest.ProtoReflect.Descriptor instead.
func (*OngkosRequest) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{16}
}

func (x *OngkosRequest) GetAsal() string {
	if x != nil {
		return x.Asal
	}
	return ""
}

func (x *OngkosRequest) GetTujuan() string {
	if x != nil {
		return x.Tujuan
	}
	return ""
}

func (x *OngkosRequest) GetBerat() int32 {
	if x != nil {
		return x.Berat
	}
	return 0
}

func (x *OngkosRequest) GetKurir() string {
	if x != nil {
		return x.Kurir
	}
	return ""
}

type RajaOngkirResponseProvinsi_Rajaongkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   []*QueryProvinsi   `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty"`
	Status  *StatusProvinsi    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Results []*ResultsProvinsi `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) Reset() {
	*x = RajaOngkirResponseProvinsi_Rajaongkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirResponseProvinsi_Rajaongkir) ProtoMessage() {}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirResponseProvinsi_Rajaongkir.ProtoReflect.Descriptor instead.
func (*RajaOngkirResponseProvinsi_Rajaongkir) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) GetQuery() []*QueryProvinsi {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) GetStatus() *StatusProvinsi {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RajaOngkirResponseProvinsi_Rajaongkir) GetResults() []*ResultsProvinsi {
	if x != nil {
		return x.Results
	}
	return nil
}

type RajaOngkirCityResponse_Rajaongkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   *QueryCity     `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Status  *StatusCity    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Results []*ResultsCity `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *RajaOngkirCityResponse_Rajaongkir) Reset() {
	*x = RajaOngkirCityResponse_Rajaongkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirCityResponse_Rajaongkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirCityResponse_Rajaongkir) ProtoMessage() {}

func (x *RajaOngkirCityResponse_Rajaongkir) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirCityResponse_Rajaongkir.ProtoReflect.Descriptor instead.
func (*RajaOngkirCityResponse_Rajaongkir) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RajaOngkirCityResponse_Rajaongkir) GetQuery() *QueryCity {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RajaOngkirCityResponse_Rajaongkir) GetStatus() *StatusCity {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RajaOngkirCityResponse_Rajaongkir) GetResults() []*ResultsCity {
	if x != nil {
		return x.Results
	}
	return nil
}

type RajaOngkirOngkosResponse_RajaOngkir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query              *Query           `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Status             *Status          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OriginDetails      *CityDetails     `protobuf:"bytes,3,opt,name=origin_details,json=originDetails,proto3" json:"origin_details,omitempty"`
	DestinationDetails *CityDetails     `protobuf:"bytes,4,opt,name=destination_details,json=destinationDetails,proto3" json:"destination_details,omitempty"`
	Results            []*CourierResult `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) Reset() {
	*x = RajaOngkirOngkosResponse_RajaOngkir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rajaongkir_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RajaOngkirOngkosResponse_RajaOngkir) ProtoMessage() {}

func (x *RajaOngkirOngkosResponse_RajaOngkir) ProtoReflect() protoreflect.Message {
	mi := &file_rajaongkir_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RajaOngkirOngkosResponse_RajaOngkir.ProtoReflect.Descriptor instead.
func (*RajaOngkirOngkosResponse_RajaOngkir) Descriptor() ([]byte, []int) {
	return file_rajaongkir_proto_rawDescGZIP(), []int{14, 0}
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) GetOriginDetails() *CityDetails {
	if x != nil {
		return x.OriginDetails
	}
	return nil
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) GetDestinationDetails() *CityDetails {
	if x != nil {
		return x.DestinationDetails
	}
	return nil
}

func (x *RajaOngkirOngkosResponse_RajaOngkir) GetResults() []*CourierResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_rajaongkir_proto protoreflect.FileDescriptor

var file_rajaongkir_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x73, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x0f,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x22, 0xfa, 0x01, 0x0a,
	0x1a, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x12, 0x49, 0x0a, 0x0a, 0x72,
	0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x2e,
	0x52, 0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x52, 0x0a, 0x72, 0x61, 0x6a, 0x61,
	0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x1a, 0x90, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6a, 0x61, 0x6f,
	0x6e, 0x67, 0x6b, 0x69, 0x72, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x73, 0x69, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x37, 0x0a, 0x09, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x43, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xe6,
	0x01, 0x0a, 0x16, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x72, 0x61, 0x6a,
	0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x6f, 0x6e,
	0x67, 0x6b, 0x69, 0x72, 0x52, 0x0a, 0x72, 0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72,
	0x1a, 0x84, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x12,
	0x23, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x69, 0x74, 0x79, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x43, 0x69, 0x74, 0x79, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x73, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb5, 0x01, 0x0a,
	0x0b, 0x43, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x48, 0x0a, 0x0a, 0x43, 0x6f, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x74, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x74, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x75,
	0x0a, 0x04, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x0c, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0b, 0x63, 0x6f, 0x73, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x57, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x05, 0x63, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x63, 0x6f, 0x73, 0x74, 0x73, 0x22, 0xde,
	0x02, 0x0a, 0x18, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x4f, 0x6e, 0x67,
	0x6b, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x72,
	0x61, 0x6a, 0x61, 0x6f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x4f,
	0x6e, 0x67, 0x6b, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x61,
	0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x52, 0x0a, 0x72, 0x61, 0x6a, 0x61, 0x6f, 0x6e,
	0x67, 0x6b, 0x69, 0x72, 0x1a, 0xf8, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67,
	0x6b, 0x69, 0x72, 0x12, 0x1f, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x40, 0x0a, 0x13, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x12,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22,
	0x1d, 0x0a, 0x0b, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67,
	0x0a, 0x0d, 0x4f, 0x6e, 0x67, 0x6b, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x73, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x73, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x75, 0x6a, 0x75, 0x61, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x75, 0x6a, 0x75, 0x61, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x65, 0x72, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x62, 0x65, 0x72, 0x61,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x75, 0x72, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6b, 0x75, 0x72, 0x69, 0x72, 0x32, 0xd0, 0x01, 0x0a, 0x11, 0x52, 0x61, 0x6a, 0x61,
	0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x73, 0x69, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e,
	0x67, 0x6b, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x73, 0x69, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b,
	0x69, 0x72, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4f,
	0x6e, 0x67, 0x6b, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x61, 0x6a, 0x61, 0x4f, 0x6e, 0x67, 0x6b, 0x69, 0x72, 0x4f, 0x6e, 0x67, 0x6b,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x62, 0x65, 0x72, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rajaongkir_proto_rawDescOnce sync.Once
	file_rajaongkir_proto_rawDescData = file_rajaongkir_proto_rawDesc
)

func file_rajaongkir_proto_rawDescGZIP() []byte {
	file_rajaongkir_proto_rawDescOnce.Do(func() {
		file_rajaongkir_proto_rawDescData = protoimpl.X.CompressGZIP(file_rajaongkir_proto_rawDescData)
	})
	return file_rajaongkir_proto_rawDescData
}

var file_rajaongkir_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_rajaongkir_proto_goTypes = []interface{}{
	(*QueryProvinsi)(nil),                         // 0: pb.QueryProvinsi
	(*StatusProvinsi)(nil),                        // 1: pb.StatusProvinsi
	(*ResultsProvinsi)(nil),                       // 2: pb.ResultsProvinsi
	(*RajaOngkirResponseProvinsi)(nil),            // 3: pb.RajaOngkirResponseProvinsi
	(*QueryCity)(nil),                             // 4: pb.QueryCity
	(*StatusCity)(nil),                            // 5: pb.StatusCity
	(*ResultsCity)(nil),                           // 6: pb.ResultsCity
	(*RajaOngkirCityResponse)(nil),                // 7: pb.RajaOngkirCityResponse
	(*Query)(nil),                                 // 8: pb.Query
	(*Status)(nil),                                // 9: pb.Status
	(*CityDetails)(nil),                           // 10: pb.CityDetails
	(*CostDetail)(nil),                            // 11: pb.CostDetail
	(*Cost)(nil),                                  // 12: pb.Cost
	(*CourierResult)(nil),                         // 13: pb.CourierResult
	(*RajaOngkirOngkosResponse)(nil),              // 14: pb.RajaOngkirOngkosResponse
	(*CityRequest)(nil),                           // 15: pb.CityRequest
	(*OngkosRequest)(nil),                         // 16: pb.OngkosRequest
	(*RajaOngkirResponseProvinsi_Rajaongkir)(nil), // 17: pb.RajaOngkirResponseProvinsi.Rajaongkir
	(*RajaOngkirCityResponse_Rajaongkir)(nil),     // 18: pb.RajaOngkirCityResponse.Rajaongkir
	(*RajaOngkirOngkosResponse_RajaOngkir)(nil),   // 19: pb.RajaOngkirOngkosResponse.RajaOngkir
	(*empty.Empty)(nil),                           // 20: google.protobuf.Empty
}
var file_rajaongkir_proto_depIdxs = []int32{
	17, // 0: pb.RajaOngkirResponseProvinsi.rajaongkir:type_name -> pb.RajaOngkirResponseProvinsi.Rajaongkir
	18, // 1: pb.RajaOngkirCityResponse.rajaongkir:type_name -> pb.RajaOngkirCityResponse.Rajaongkir
	11, // 2: pb.Cost.cost_details:type_name -> pb.CostDetail
	12, // 3: pb.CourierResult.costs:type_name -> pb.Cost
	19, // 4: pb.RajaOngkirOngkosResponse.rajaongkir:type_name -> pb.RajaOngkirOngkosResponse.RajaOngkir
	0,  // 5: pb.RajaOngkirResponseProvinsi.Rajaongkir.query:type_name -> pb.QueryProvinsi
	1,  // 6: pb.RajaOngkirResponseProvinsi.Rajaongkir.status:type_name -> pb.StatusProvinsi
	2,  // 7: pb.RajaOngkirResponseProvinsi.Rajaongkir.results:type_name -> pb.ResultsProvinsi
	4,  // 8: pb.RajaOngkirCityResponse.Rajaongkir.query:type_name -> pb.QueryCity
	5,  // 9: pb.RajaOngkirCityResponse.Rajaongkir.status:type_name -> pb.StatusCity
	6,  // 10: pb.RajaOngkirCityResponse.Rajaongkir.results:type_name -> pb.ResultsCity
	8,  // 11: pb.RajaOngkirOngkosResponse.RajaOngkir.query:type_name -> pb.Query
	9,  // 12: pb.RajaOngkirOngkosResponse.RajaOngkir.status:type_name -> pb.Status
	10, // 13: pb.RajaOngkirOngkosResponse.RajaOngkir.origin_details:type_name -> pb.CityDetails
	10, // 14: pb.RajaOngkirOngkosResponse.RajaOngkir.destination_details:type_name -> pb.CityDetails
	13, // 15: pb.RajaOngkirOngkosResponse.RajaOngkir.results:type_name -> pb.CourierResult
	20, // 16: pb.RajaOngkirService.GetProvinsi:input_type -> google.protobuf.Empty
	15, // 17: pb.RajaOngkirService.GetCities:input_type -> pb.CityRequest
	16, // 18: pb.RajaOngkirService.GetCost:input_type -> pb.OngkosRequest
	3,  // 19: pb.RajaOngkirService.GetProvinsi:output_type -> pb.RajaOngkirResponseProvinsi
	7,  // 20: pb.RajaOngkirService.GetCities:output_type -> pb.RajaOngkirCityResponse
	14, // 21: pb.RajaOngkirService.GetCost:output_type -> pb.RajaOngkirOngkosResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_rajaongkir_proto_init() }
func file_rajaongkir_proto_init() {
	if File_rajaongkir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rajaongkir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProvinsi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusProvinsi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultsProvinsi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirResponseProvinsi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultsCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirOngkosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OngkosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirResponseProvinsi_Rajaongkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirCityResponse_Rajaongkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rajaongkir_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RajaOngkirOngkosResponse_RajaOngkir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rajaongkir_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rajaongkir_proto_goTypes,
		DependencyIndexes: file_rajaongkir_proto_depIdxs,
		MessageInfos:      file_rajaongkir_proto_msgTypes,
	}.Build()
	File_rajaongkir_proto = out.File
	file_rajaongkir_proto_rawDesc = nil
	file_rajaongkir_proto_goTypes = nil
	file_rajaongkir_proto_depIdxs = nil
}
