// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: slider.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Slider) Reset() {
	*x = Slider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slider) ProtoMessage() {}

func (x *Slider) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slider.ProtoReflect.Descriptor instead.
func (*Slider) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{0}
}

func (x *Slider) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Slider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slider) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type SliderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SliderRequest) Reset() {
	*x = SliderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliderRequest) ProtoMessage() {}

func (x *SliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliderRequest.ProtoReflect.Descriptor instead.
func (*SliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{1}
}

func (x *SliderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SlidersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sliders []*Slider `protobuf:"bytes,1,rep,name=sliders,proto3" json:"sliders,omitempty"`
}

func (x *SlidersResponse) Reset() {
	*x = SlidersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlidersResponse) ProtoMessage() {}

func (x *SlidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlidersResponse.ProtoReflect.Descriptor instead.
func (*SlidersResponse) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{2}
}

func (x *SlidersResponse) GetSliders() []*Slider {
	if x != nil {
		return x.Sliders
	}
	return nil
}

type SliderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slider *Slider `protobuf:"bytes,1,opt,name=slider,proto3" json:"slider,omitempty"`
}

func (x *SliderResponse) Reset() {
	*x = SliderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SliderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliderResponse) ProtoMessage() {}

func (x *SliderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliderResponse.ProtoReflect.Descriptor instead.
func (*SliderResponse) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{3}
}

func (x *SliderResponse) GetSlider() *Slider {
	if x != nil {
		return x.Slider
	}
	return nil
}

type CreateSliderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *CreateSliderRequest) Reset() {
	*x = CreateSliderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliderRequest) ProtoMessage() {}

func (x *CreateSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliderRequest.ProtoReflect.Descriptor instead.
func (*CreateSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSliderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSliderRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type UpdateSliderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *UpdateSliderRequest) Reset() {
	*x = UpdateSliderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliderRequest) ProtoMessage() {}

func (x *UpdateSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliderRequest.ProtoReflect.Descriptor instead.
func (*UpdateSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSliderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSliderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSliderRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeleteSliderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteSliderResponse) Reset() {
	*x = DeleteSliderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_slider_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSliderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSliderResponse) ProtoMessage() {}

func (x *DeleteSliderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSliderResponse.ProtoReflect.Descriptor instead.
func (*DeleteSliderResponse) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSliderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_slider_proto protoreflect.FileDescriptor

var file_slider_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x42, 0x0a, 0x06, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x73, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x07, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x73, 0x22, 0x34, 0x0a,
	0x0e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x06, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x06, 0x73, 0x6c, 0x69,
	0x64, 0x65, 0x72, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x69,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xb5, 0x02, 0x0a, 0x0d, 0x53, 0x6c, 0x69, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x64,
	0x65, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1d, 0x5a, 0x1b, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x62,
	0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slider_proto_rawDescOnce sync.Once
	file_slider_proto_rawDescData = file_slider_proto_rawDesc
)

func file_slider_proto_rawDescGZIP() []byte {
	file_slider_proto_rawDescOnce.Do(func() {
		file_slider_proto_rawDescData = protoimpl.X.CompressGZIP(file_slider_proto_rawDescData)
	})
	return file_slider_proto_rawDescData
}

var file_slider_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_slider_proto_goTypes = []interface{}{
	(*Slider)(nil),               // 0: pb.Slider
	(*SliderRequest)(nil),        // 1: pb.SliderRequest
	(*SlidersResponse)(nil),      // 2: pb.SlidersResponse
	(*SliderResponse)(nil),       // 3: pb.SliderResponse
	(*CreateSliderRequest)(nil),  // 4: pb.CreateSliderRequest
	(*UpdateSliderRequest)(nil),  // 5: pb.UpdateSliderRequest
	(*DeleteSliderResponse)(nil), // 6: pb.DeleteSliderResponse
	(*empty.Empty)(nil),          // 7: google.protobuf.Empty
}
var file_slider_proto_depIdxs = []int32{
	0, // 0: pb.SlidersResponse.sliders:type_name -> pb.Slider
	0, // 1: pb.SliderResponse.slider:type_name -> pb.Slider
	7, // 2: pb.SliderService.GetSliders:input_type -> google.protobuf.Empty
	1, // 3: pb.SliderService.GetSlider:input_type -> pb.SliderRequest
	4, // 4: pb.SliderService.CreateSlider:input_type -> pb.CreateSliderRequest
	5, // 5: pb.SliderService.UpdateSlider:input_type -> pb.UpdateSliderRequest
	1, // 6: pb.SliderService.DeleteSlider:input_type -> pb.SliderRequest
	2, // 7: pb.SliderService.GetSliders:output_type -> pb.SlidersResponse
	3, // 8: pb.SliderService.GetSlider:output_type -> pb.SliderResponse
	3, // 9: pb.SliderService.CreateSlider:output_type -> pb.SliderResponse
	3, // 10: pb.SliderService.UpdateSlider:output_type -> pb.SliderResponse
	6, // 11: pb.SliderService.DeleteSlider:output_type -> pb.DeleteSliderResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_slider_proto_init() }
func file_slider_proto_init() {
	if File_slider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_slider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SliderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlidersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SliderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSliderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSliderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_slider_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSliderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slider_proto_goTypes,
		DependencyIndexes: file_slider_proto_depIdxs,
		MessageInfos:      file_slider_proto_msgTypes,
	}.Build()
	File_slider_proto = out.File
	file_slider_proto_rawDesc = nil
	file_slider_proto_goTypes = nil
	file_slider_proto_depIdxs = nil
}
